
package ventanas;

import clases.BaseDeDatos;
import clases.Disennio;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author luism
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Administrador");
        Disennio wallpaperUrl = new Disennio();
        
        ImageIcon wallpaper = new ImageIcon(new ImageIcon(wallpaperUrl.getWallpaper()).getImage()
                .getScaledInstance(labelWallpaper.getWidth(), labelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        labelWallpaper.setIcon(wallpaper);
    }
    
    @Override
    public Image getIconImage(){
        Disennio icono = new Disennio();
        return icono.getIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAggProducto = new javax.swing.JButton();
        botonGestionProducto = new javax.swing.JButton();
        botonRegistroEmpl = new javax.swing.JButton();
        botonGestionEmpl = new javax.swing.JButton();
        bontonVentas = new javax.swing.JButton();
        botonInventario = new javax.swing.JButton();
        botonCrearBaseDeDatos = new javax.swing.JButton();
        botonCaja = new javax.swing.JButton();
        botonLibros = new javax.swing.JButton();
        labelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAggProducto.setText("Agg Producto");
        botonAggProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonAggProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAggProductoActionPerformed(evt);
            }
        });
        getContentPane().add(botonAggProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 70));

        botonGestionProducto.setText("Gestion Producto");
        botonGestionProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonGestionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionProductoActionPerformed(evt);
            }
        });
        getContentPane().add(botonGestionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 70));

        botonRegistroEmpl.setText("Registrar Empleado");
        botonRegistroEmpl.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonRegistroEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroEmplActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistroEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 80, 70));

        botonGestionEmpl.setText("Gestionoar Empleado");
        botonGestionEmpl.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonGestionEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionEmplActionPerformed(evt);
            }
        });
        getContentPane().add(botonGestionEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 80, 70));

        bontonVentas.setText("Venrtas");
        bontonVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bontonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontonVentasActionPerformed(evt);
            }
        });
        getContentPane().add(bontonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, 70));

        botonInventario.setText("Inventario");
        botonInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 80, 70));

        botonCrearBaseDeDatos.setText("Crear Base de Datos");
        botonCrearBaseDeDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonCrearBaseDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearBaseDeDatosActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 80, 70));

        botonCaja.setText("Caja");
        botonCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 80, 70));

        botonLibros.setText("Sistema");
        botonLibros.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(botonLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 80, 70));
        getContentPane().add(labelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionEmplActionPerformed
       
        try {
            new ListadoDeEmpleados().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonGestionEmplActionPerformed

    private void botonRegistroEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroEmplActionPerformed
        
        new RegistrarDeEmpleado().setVisible(true);
        
    }//GEN-LAST:event_botonRegistroEmplActionPerformed

    private void botonCrearBaseDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearBaseDeDatosActionPerformed
  
        try {
            new BaseDeDatos().crearBaseDeDatos();
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonCrearBaseDeDatosActionPerformed

    private void botonAggProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAggProductoActionPerformed

        new RegistrarProducto().setVisible(true);
        
    }//GEN-LAST:event_botonAggProductoActionPerformed

    private void botonGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionProductoActionPerformed
       
        new ListadoDeProductos().setVisible(true);
    }//GEN-LAST:event_botonGestionProductoActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        
        new Inventario().setVisible(true);
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void bontonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontonVentasActionPerformed
        
        new Ventas().setVisible(true);
    }//GEN-LAST:event_bontonVentasActionPerformed

    private void botonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajaActionPerformed
        
        new Caja().setVisible(true);
    }//GEN-LAST:event_botonCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonVentas;
    private javax.swing.JButton botonAggProducto;
    private javax.swing.JButton botonCaja;
    private javax.swing.JButton botonCrearBaseDeDatos;
    private javax.swing.JButton botonGestionEmpl;
    private javax.swing.JButton botonGestionProducto;
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonLibros;
    private javax.swing.JButton botonRegistroEmpl;
    private javax.swing.JLabel labelWallpaper;
    // End of variables declaration//GEN-END:variables
}
