package ventanas;

import clases.Buscar;
import clases.Disennio;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luism
 */
public class Caja extends javax.swing.JFrame {

    private double dolar = PrecioDolar.getDolar();
    private static String codigo;
    private String[] datos;
    private String codg;
    private String nombre;
    private String marca;
    private String precioDoll;
    private String precioBs;
    private String cantidad;
    private double totalDoll;
    private double totalBs;
    DefaultTableModel tableModel;

    /**
     * Creates new form Caja
     */
    public Caja() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Caja");
        Disennio wallpaperUrl = new Disennio();

        ImageIcon wallpaper = new ImageIcon(new ImageIcon(wallpaperUrl.getWallpaper()).getImage()
                .getScaledInstance(labelWallpaper.getWidth(), labelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        labelWallpaper.setIcon(wallpaper);

        llenadoTabla();

    }

    @Override
    public Image getIconImage() {
        Disennio icono = new Disennio();
        return icono.getIconImage();
    }

    public void llenadoTabla() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Marca");
        tableModel.addColumn("Cantidad");
        tableModel.addColumn("Precio $.");
        tableModel.addColumn("Precio Bs.");
        
        tabla.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelTotalDoll = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        botonDetalle = new javax.swing.JButton();
        botonagregar = new javax.swing.JButton();
        labelTotalBs = new javax.swing.JLabel();
        labelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(710, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 34, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 54, 111, -1));

        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 34, -1, -1));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 54, 70, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 92, 474, -1));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 542, -1, -1));

        labelTotalDoll.setText("Total $: ");
        getContentPane().add(labelTotalDoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 92, 130, 30));

        jButton2.setText("Cobrar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        botonDetalle.setText("Detalle");
        getContentPane().add(botonDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));

        botonagregar.setText("Agregar");
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        labelTotalBs.setText("Total Bs:");
        getContentPane().add(labelTotalBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 130, 30));

        labelWallpaper.setText("jLabel1");
        getContentPane().add(labelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -5, 710, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed

        if (txtCodigo.getText().equals("") || txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe introducir un codigo");
        } else {
            cargarProducto();
        }


    }//GEN-LAST:event_botonagregarActionPerformed


    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botonagregar.doClick();
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botonagregar.doClick();
        }

    }//GEN-LAST:event_txtCantidadKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = tabla.getSelectedRow();
        tableModel.removeRow(fila);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargarProducto() {

        codigo = txtCodigo.getText();
        new Buscar().buscarCodigo();
        datos = Buscar.getDatos();

        codg = datos[0];
        nombre = datos[1];
        marca = datos[2];
        precioDoll = datos[4];
        cantidad = datos[5];

        String cantidades = String.valueOf(txtCantidad.getText());
        double cantidadesNum = Double.parseDouble(cantidades);
        double precioFinalDoll = Double.parseDouble(precioDoll);
        double precioFinalBs = precioFinalDoll * dolar;

        if (cantidadesNum > 1) {
            precioFinalDoll = precioFinalDoll * cantidadesNum;
            precioFinalBs = precioFinalBs * cantidadesNum;
        }

        totalDoll =  totalDoll + precioFinalDoll;
        totalBs =  (totalBs + precioFinalBs);
        labelTotalDoll.setText("Total $:  " + String.valueOf(totalDoll));
        labelTotalBs.setText("Total Bs: "+ String.valueOf((int)totalBs));

        //Tabla de ventas
        String[] articulo = new String[5];
        articulo[0] = nombre;
        articulo[1] = marca;
        articulo[2] = cantidades;
        articulo[3] = precioDoll;
        articulo[4] = String.valueOf((int)(Double.parseDouble(precioDoll) * dolar));

        tableModel.addRow(articulo);
        tabla.setModel(tableModel);

        txtCodigo.setText("");
        txtCantidad.setText("");
    }

    public static String getCodigo() {
        return codigo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetalle;
    private javax.swing.JButton botonagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalBs;
    private javax.swing.JLabel labelTotalDoll;
    private javax.swing.JLabel labelWallpaper;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCantidad;
    private static javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
